"""Add MatchingCycle table

Revision ID: 56fad05fbe24
Revises: bedef77da9b0
Create Date: 2025-04-11 17:08:41.703342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fad05fbe24'
down_revision = 'bedef77da9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('survey_start_date', sa.DateTime(), nullable=False),
    sa.Column('survey_end_date', sa.DateTime(), nullable=False),
    sa.Column('processing_end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_cycles')
    # ### end Alembic commands ###
