"""Update matches table columns

Revision ID: bedef77da9b0
Revises: 1f23ce5afe24
Create Date: 2025-04-09 18:54:10.586770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bedef77da9b0'
down_revision = '1f23ce5afe24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user2_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('unique_match_pair', ['user1_email', 'user2_email'])
        batch_op.drop_constraint('matches_user_id2_fkey', type_='foreignkey')
        batch_op.drop_constraint('matches_user_id1_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user2_email'], ['email'])
        batch_op.create_foreign_key(None, 'users', ['user1_email'], ['email'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id1')
        batch_op.drop_column('match_score')
        batch_op.drop_column('user_id2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('matches_user_id1_fkey', 'users', ['user_id1'], ['id'])
        batch_op.create_foreign_key('matches_user_id2_fkey', 'users', ['user_id2'], ['id'])
        batch_op.drop_constraint('unique_match_pair', type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('date_created')
        batch_op.drop_column('score')
        batch_op.drop_column('user2_email')
        batch_op.drop_column('user1_email')

    # ### end Alembic commands ###
