"""Add cycle_id to matches table

Revision ID: e3da681e663c
Revises: 56fad05fbe24
Create Date: 2025-04-11 22:27:45.813862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3da681e663c'
down_revision = '56fad05fbe24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'matching_cycles', ['cycle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cycle_id')

    # ### end Alembic commands ###
